// Deploys SupplyChain.sol to the configured network (default: sepolia).
// Saves ABI + address into ../src/lib/contract-config.ts and ./deployments/<network>.json
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  const network = hre.network.name;
  console.log(`\n🚀 Deploying SupplyChain to network: ${network}`);

  const [deployer] = await hre.ethers.getSigners();
  console.log(`Deployer: ${deployer.address}`);
  const bal = await hre.ethers.provider.getBalance(deployer.address);
  console.log(`Balance:  ${hre.ethers.formatEther(bal)} ETH`);

  const Factory = await hre.ethers.getContractFactory("SupplyChain");
  const contract = await Factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log(`✅ SupplyChain deployed at: ${address}`);

  // Read ABI from artifacts
  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "SupplyChain.sol",
    "SupplyChain.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;

  // Write deployments record
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });
  fs.writeFileSync(
    path.join(deploymentsDir, `${network}.json`),
    JSON.stringify({ network, address, deployer: deployer.address, deployedAt: new Date().toISOString() }, null, 2)
  );

  // Write the frontend contract config
  const frontendConfigPath = path.join(__dirname, "..", "..", "src", "lib", "contract-config.ts");
  const chainId = network === "sepolia" ? 11155111 : (hre.network.config.chainId || 0);
  const networkName = network === "sepolia" ? "Sepolia" : network;

  const fileContent = `// AUTO-GENERATED by blockchain/scripts/deploy.js
// Frontend contract configuration. Safe to commit.
export const CONTRACT_ADDRESS = "${address}";
export const NETWORK_NAME = "${networkName}";
export const CHAIN_ID = ${chainId};
export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)} as const;
`;
  fs.mkdirSync(path.dirname(frontendConfigPath), { recursive: true });
  fs.writeFileSync(frontendConfigPath, fileContent);
  console.log(`📝 Wrote frontend config -> ${frontendConfigPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
